name: Maven-Tomcat CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        mvn clean
        mvn package

    - name: Deploy to Tomcat
      env:
        TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
        TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
      run: |
        WAR_FILE=$(find target -name "*.war" | head -n 1)
        curl -v --upload-file "$WAR_FILE" "http://$TOMCAT_USERNAME:$TOMCAT_PASSWORD@44.210.89.8:8081/manager/text/deploy?path=/myapp&update=true"
